export const THEMES = {
  classic: {
    name: 'Classic',
    tag: 'A · Light · Blue',
    mode: 'light',
    fontUI: '"Inter", system-ui, -apple-system, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    vars: {
      '--bg':           '#f6f7f9',
      '--bg-2':         '#ffffff',
      '--bg-3':         '#eef0f4',
      '--bg-rail':      '#1f2937',
      '--bg-rail-2':    '#111827',
      '--bg-sidebar':   '#f1f3f7',
      '--bg-titlebar':  '#e6e9ee',
      '--border':       '#dadfe6',
      '--border-soft':  '#e7eaef',
      '--border-strong':'#c1c7d0',
      '--text':         '#1a1f29',
      '--text-2':       '#4b5565',
      '--text-3':       '#7a8597',
      '--text-rail':    '#cbd2dc',
      '--text-rail-mute':'#7c8696',
      '--accent':       '#2563eb',
      '--accent-soft':  '#dbe6fe',
      '--accent-text':  '#1e40af',
      '--ok':           '#0d9c6e',
      '--warn':         '#c2680b',
      '--err':          '#d93b3b',
      '--row-hover':    '#f3f6fb',
      '--row-selected': '#dbeafe',
      '--cell-edit':    '#fff7d6',
      '--kw':           '#7c3aed',
      '--str':          '#0d9c6e',
      '--num':          '#c2680b',
      '--fn':           '#2563eb',
      '--comment':      '#94a3b8',
      '--shadow':       '0 1px 0 rgba(15,23,42,.04), 0 8px 24px -12px rgba(15,23,42,.18)',
      '--radius':       '6px',
      '--row-h':        '28px',
    },
  },
  console: {
    name: 'Console',
    tag: 'B · Dark · Cyan',
    mode: 'dark',
    fontUI: '"Inter", system-ui, -apple-system, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    vars: {
      '--bg':           '#0e1116',
      '--bg-2':         '#151a21',
      '--bg-3':         '#1c222b',
      '--bg-rail':      '#080a0d',
      '--bg-rail-2':    '#05070a',
      '--bg-sidebar':   '#10141a',
      '--bg-titlebar':  '#0a0d12',
      '--border':       '#252c36',
      '--border-soft':  '#1d232c',
      '--border-strong':'#384252',
      '--text':         '#dde3ec',
      '--text-2':       '#9aa5b4',
      '--text-3':       '#5c6776',
      '--text-rail':    '#9aa5b4',
      '--text-rail-mute':'#4d5663',
      '--accent':       '#22d3ee',
      '--accent-soft':  '#0e3a44',
      '--accent-text':  '#67e8f9',
      '--ok':           '#34d399',
      '--warn':         '#fbbf24',
      '--err':          '#f87171',
      '--row-hover':    '#181f28',
      '--row-selected': '#102d34',
      '--cell-edit':    '#2a2616',
      '--kw':           '#c084fc',
      '--str':          '#34d399',
      '--num':          '#fbbf24',
      '--fn':           '#22d3ee',
      '--comment':      '#5c6776',
      '--shadow':       '0 0 0 1px rgba(0,0,0,.4), 0 12px 28px -10px rgba(0,0,0,.7)',
      '--radius':       '5px',
      '--row-h':        '26px',
    },
  },
  workbench: {
    name: 'Workbench',
    tag: 'C · Warm · Amber',
    mode: 'light',
    fontUI: '"IBM Plex Sans", system-ui, sans-serif',
    fontMono: '"IBM Plex Mono", ui-monospace, Menlo, monospace',
    vars: {
      '--bg':           '#f4efe6',
      '--bg-2':         '#fbf7f0',
      '--bg-3':         '#ece5d6',
      '--bg-rail':      '#2a2520',
      '--bg-rail-2':    '#1f1c18',
      '--bg-sidebar':   '#ede6d6',
      '--bg-titlebar':  '#e3dcca',
      '--border':       '#d6cdb8',
      '--border-soft':  '#e3dcca',
      '--border-strong':'#beb39c',
      '--text':         '#2a2520',
      '--text-2':       '#5b5145',
      '--text-3':       '#857b6c',
      '--text-rail':    '#d6cdb8',
      '--text-rail-mute':'#867d6e',
      '--accent':       '#c2680b',
      '--accent-soft':  '#f4e3c2',
      '--accent-text':  '#8a4a08',
      '--ok':           '#3f7d4e',
      '--warn':         '#b6791d',
      '--err':          '#b3402c',
      '--row-hover':    '#efe7d4',
      '--row-selected': '#f3dfb3',
      '--cell-edit':    '#fff2c9',
      '--kw':           '#8a4a08',
      '--str':          '#3f7d4e',
      '--num':          '#b3402c',
      '--fn':           '#7a5ae0',
      '--comment':      '#a59881',
      '--shadow':       '0 1px 0 rgba(60,40,20,.06), 0 12px 28px -14px rgba(60,40,20,.25)',
      '--radius':       '4px',
      '--row-h':        '30px',
    },
  },
};
